package com.zentrapay.service;

import com.zentrapay.dto.auth.AuthResponse;
import com.zentrapay.dto.auth.LoginRequest;
import com.zentrapay.dto.auth.RegisterRequest;
import com.zentrapay.entity.EmailVerificationToken;
import com.zentrapay.entity.User;
import com.zentrapay.exception.DuplicateResourceException;
import com.zentrapay.exception.EmailNotVerifiedException;
import com.zentrapay.exception.InvalidCredentialsException;
import com.zentrapay.repository.EmailVerificationTokenRepository;
import com.zentrapay.repository.UserRepository;
import com.zentrapay.util.JwtUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.UUID;
import java.util.UUID;

/**
 * Authentication Service
 *
 * Handles:
 * - User registration
 * - User login
 * - JWT token generation
 *
 * Business Logic Layer:
 * - Contains all authentication rules
 * - Validates data
 * - Hashes passwords
 * - Generates tokens
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class AuthService {

    // Dependencies injected by Spring (constructor injection)
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;
    private final EmailVerificationTokenRepository tokenRepository;
    private final EmailService emailService;

    /**
     * Register new user
     *
     * Process:
     * 1. Check email doesn't exist (prevent duplicates)
     * 2. Hash password with BCrypt
     * 3. Create user entity
     * 4. Save to database
     * 5. Generate JWT token
     * 6. Return response
     *
     * @param request Registration data (email, password, fullName)
     * @return AuthResponse with token and user info
     * @throws DuplicateResourceException if email already exists
     */
    @Transactional
    public AuthResponse register(RegisterRequest request) {
        log.info("Registration attempt for email: {}", request.getEmail());

        // STEP 1: Check if email already exists
        if (userRepository.existsByEmail(request.getEmail())) {
            log.warn("Registration failed - email already exists: {}",
                    request.getEmail());
            throw new DuplicateResourceException("Email already registered");
        }

        // STEP 2: Hash the password
        // BCrypt turns "MyPassword123" into "$2a$12$xyz..."
        // Even if database is hacked, passwords are safe
        String hashedPassword = passwordEncoder.encode(request.getPassword());

        // STEP 3: Create the user
        User user = new User();
        user.setEmail(request.getEmail().toLowerCase().trim());
        user.setPasswordHash(hashedPassword);
        user.setFullName(request.getFullName().trim());
        user.setEmailVerified(false);

        // STEP 4: Save user and reload to get database-generated values
        // (createdAt, updatedAt are generated by the database)
        userRepository.save(user);
        User savedUser = userRepository.findById(user.getId())
                .orElseThrow(() -> new RuntimeException("User not found after save"));

        log.info("User created with id: {}", savedUser.getId());

        // STEP 5: Create verification token
        // We generate a long random string as the token
        // This is what goes in the email link
        String verificationToken = generateVerificationToken();

        EmailVerificationToken emailToken = new EmailVerificationToken();
        emailToken.setUser(savedUser);
        emailToken.setToken(verificationToken);
        emailToken.setExpiresAt(LocalDateTime.now().plusHours(24));
        tokenRepository.save(emailToken);

        log.info("Verification token created for user: {}", savedUser.getId());

        // STEP 6: Send verification email
        // We pass the token - EmailService builds the full URL
        emailService.sendVerificationEmail(
                savedUser.getEmail(),
                savedUser.getFullName(),
                verificationToken
        );

        // STEP 7: Generate JWT token for immediate use
        String token = jwtUtil.generateToken(
                savedUser.getId(),
                savedUser.getEmail()
        );

        // STEP 8: Return response
        return buildAuthResponse(savedUser, token);
    }
    /**
     * Authenticate user (login)
     *
     * Process:
     * 1. Find user by email
     * 2. Verify password matches
     * 3. Check email is verified
     * 4. Generate JWT token
     * 5. Return response
     *
     * @param request Login credentials (email, password)
     * @return AuthResponse with token and user info
     * @throws InvalidCredentialsException if email/password wrong
     * @throws EmailNotVerifiedException if email not verified
     */
    @Transactional(readOnly = true)
    public AuthResponse login(LoginRequest request) {
        log.info("Login attempt for email: {}", request.getEmail());

        // STEP 1: Find user by email
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> {
                    log.warn("Login failed - user not found: {}", request.getEmail());
                    return new InvalidCredentialsException("Invalid email or password");
                });

        // STEP 2: Verify password
        if (!passwordEncoder.matches(request.getPassword(), user.getPasswordHash())) {
            log.warn("Login failed - wrong password: {}", request.getEmail());
            throw new InvalidCredentialsException("Invalid email or password");
        }

        // STEP 3: Check email verified
        if (!user.getEmailVerified()) {
            log.warn("Login failed - email not verified: {}", request.getEmail());
            throw new EmailNotVerifiedException(
                    "Please verify your email before logging in"
            );
        }

        log.info("Login successful: {}", user.getId());

        // STEP 4: Generate token
        String token = jwtUtil.generateToken(user.getId(), user.getEmail());

        // STEP 5: Return response
        return buildAuthResponse(user, token);
    }

    /**
     * Helper: Build authentication response
     *
     * Creates AuthResponse with:
     * - JWT token
     * - Token type (Bearer)
     * - Expiration time
     * - User info (NO password hash!)
     *
     * @param user User entity
     * @param token JWT token
     * @return AuthResponse
     */
    private AuthResponse buildAuthResponse(User user, String token) {
        // Build user DTO (only safe fields)
        AuthResponse.UserDTO userDTO = AuthResponse.UserDTO.builder()
                .id(user.getId())
                .email(user.getEmail())
                .fullName(user.getFullName())
                .emailVerified(user.getEmailVerified())
                .createdAt(user.getCreatedAt())
                .build();

        // Build auth response
        return AuthResponse.builder()
                .token(token)
                .tokenType("Bearer")
                .expiresAt(jwtUtil.getExpirationTime())
                .user(userDTO)
                .build();
    }
    /**
     * Verify user email using token
     *
     * Process:
     * 1. Find token in database
     * 2. Check token is valid (not used, not expired)
     * 3. Mark user email as verified
     * 4. Mark token as used
     *
     * @param token The verification token from the email link
     * @throws RuntimeException if token invalid, used, or expired
     */
    @Transactional
    public void verifyEmail(String token) {
        log.info("Email verification attempt with token: {}...",
                token.substring(0, 8));

        // STEP 1: Find token in database
        EmailVerificationToken verificationToken = tokenRepository
                .findByToken(token)
                .orElseThrow(() -> {
                    log.warn("Verification failed - token not found");
                    return new RuntimeException("Invalid verification token");
                });

        // STEP 2: Check token not already used
        // Prevents someone using the same link twice
        if (verificationToken.getUsed()) {
            log.warn("Verification failed - token already used");
            throw new RuntimeException(
                    "This verification link has already been used"
            );
        }

        // STEP 3: Check token not expired
        // Tokens expire after 24 hours
        if (verificationToken.isExpired()) {
            log.warn("Verification failed - token expired");
            throw new RuntimeException(
                    "This verification link has expired. Please register again."
            );
        }

        // STEP 4: Mark email as verified
        User user = verificationToken.getUser();
        user.setEmailVerified(true);
        userRepository.save(user);

        // STEP 5: Mark token as used
        // So the same link cannot be used again
        verificationToken.setUsed(true);
        tokenRepository.save(verificationToken);

        log.info("Email verified successfully for user: {}", user.getId());
    }

    /**
     * Generate a secure random verification token
     *
     * We combine two UUIDs and remove hyphens.
     * Result: 64 character random string
     * Example: "a1b2c3d4e5f6...8z9y"
     *
     * Why two UUIDs?
     * More characters = harder to guess = more secure
     */
    private String generateVerificationToken() {
        return UUID.randomUUID().toString().replace("-", "")
                + UUID.randomUUID().toString().replace("-", "");
    }
}