package com.zentrapay.repository;

import com.zentrapay.entity.BankAccount;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Repository for bank accounts
 *
 * Spring Data JPA automatically implements these methods.
 * We just define what we need, Spring writes the SQL.
 *
 * Why each method?
 * See comments below.
 */
@Repository
public interface BankAccountRepository
        extends JpaRepository<BankAccount, UUID> {

    /**
     * Find seller's bank account by user ID
     *
     * Used when:
     * - User creates a payment link (need their bank account)
     * - User views their settings (show their bank account)
     * - User updates their bank account
     *
     * SQL generated by Spring:
     * SELECT * FROM bank_accounts WHERE user_id = ?
     *
     * @param userId The user's UUID
     * @return Optional with bank account if exists
     */
    Optional<BankAccount> findByUserId(UUID userId);

    /**
     * Check if user already has a bank account
     *
     * Used when:
     * - User tries to add first bank account (should succeed)
     * - User tries to add second bank account (should fail - one per seller)
     *
     * SQL generated by Spring:
     * SELECT EXISTS(SELECT 1 FROM bank_accounts WHERE user_id = ?)
     *
     * @param userId The user's UUID
     * @return true if account exists, false if not
     */
    boolean existsByUserId(UUID userId);

    /**
     * Find bank account by Paystack subaccount code
     *
     * Used when:
     * - Webhook from Paystack arrives (tells us which subaccount got paid)
     * - We need to find the seller to credit the payment
     *
     * SQL generated by Spring:
     * SELECT * FROM bank_accounts WHERE paystack_subaccount_code = ?
     *
     * @param subaccountCode The Paystack subaccount code
     * @return Optional with bank account if exists
     */
    Optional<BankAccount> findByPaystackSubaccountCode(String subaccountCode);
}