package com.zentrapay.repository;

import com.zentrapay.entity.EmailVerificationToken;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Repository for email verification tokens
 *
 * Spring Data JPA automatically implements these methods.
 * We just define what we need, Spring writes the SQL.
 */
@Repository
public interface EmailVerificationTokenRepository
        extends JpaRepository<EmailVerificationToken, UUID> {

    /**
     * Find a token by its string value
     *
     * Used when user clicks the verification link.
     * We extract the token from the URL and look it up here.
     *
     * SQL generated by Spring:
     * SELECT * FROM email_verification_tokens WHERE token = ?
     */
    Optional<EmailVerificationToken> findByToken(String token);

    /**
     * Delete all tokens for a specific user
     *
     * Used when user re-registers or requests a new verification email.
     * We delete old tokens before creating a new one.
     *
     * SQL generated by Spring:
     * DELETE FROM email_verification_tokens WHERE user_id = ?
     */
    void deleteByUserId(UUID userId);
}